# SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

monolog:
    channels: ['audit_platform', 'audit_delivery_execution', 'deprecation']
    handlers:
        system:
            level: debug
            type: stream
            path: "php://stdout"
            channels: ['!audit_platform', '!audit_delivery_execution', '!deprecation']
            formatter: monolog.formatter.gcloud_json
        audit_platform:
            level: debug
            type: stream
            path: "php://stdout"
            channels: ['audit_platform']
            formatter: monolog.formatter.gcloud_json
        audit_delivery_execution:
            level: debug
            type: stream
            path: "php://stdout"
            channels: ['audit_delivery_execution']
            formatter: monolog.formatter.gcloud_json
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console', '!deprecation']
            formatter: monolog.formatter.gcloud_json
        deprecation:
            bubble: false
            type: "null"
            channels: [deprecation]   
