# SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

health_check_check:
    resource: '@HealthCheckBundle/Resources/config/routing/health_check_check.yaml'

health_check_ping:
    resource: '@HealthCheckBundle/Resources/config/routing/health_check_ping.yaml'
