# SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

lti1p3_message_platform:
    resource: '@Lti1p3Bundle/Resources/config/routing/message/platform.yaml'
