# SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

document_manager:
  connections:
    bigtable_connection:
      driver: gcp-bigtable
      options:
        instanceId:
          value: '%env(GOOGLE_CLOUD_BIGTABLE_INSTANCE)%'
        appProfileId:
          value: '%env(GOOGLE_CLOUD_BIGTABLE_APP_PROFILE)%'

    elasticsearch_connection:
      driver: cached-elasticsearch
      options: [ ]

  handlers:
    deliver_handler:
      connection: elasticsearch_connection

    battery_handler:
      connection: elasticsearch_connection

    delivery_execution_alias_handler:
      connection: bigtable_connection

    battery_distribution_handler:
      connection: bigtable_connection

    delivery_execution_handler:
      connection: bigtable_connection

    publication_handler:
      connection: bigtable_connection
