# SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

services:
    _defaults:
        autowire: true
        autoconfigure: true

    OAT\Library\EnvironmentManagementClient\Repository\FeatureFlagRepositoryInterface:
        class: App\Tests\Stubs\FeatureFlagRepositoryStub
        public: true

    OAT\Library\EnvironmentManagementClient\Repository\ConfigurationRepositoryInterface:
      class: App\Tests\Stubs\ConfigurationRepositoryStub
      public: true

    OAT\Library\TaoTimerClient\Service\TimerServiceInterface:
      class: App\Tests\Stubs\StubTimerService
