# SPDX-FileCopyrightText: 2012-2026 Open Assessment Technologies S.A.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-TAO-Commercial-License

parameters:
  default.acs_reference_type: !php/const Symfony\Component\Routing\Generator\UrlGeneratorInterface::NETWORK_PATH

services:
  _defaults:
    autowire: true
    autoconfigure: true

  lock.store.optional:
    class: Symfony\Component\Lock\Store\RedisStore
    arguments:
      - '@cache.provider.shared_redis'
      - 10
  App\Service\Lti\LtiProctoringService:
    arguments:
      $acsUrlReferenceType: '%env(int:default:default.acs_reference_type:ACS_REF_TYPE)%'
